version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./:/app
  
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    ports:
      - ${APP_PORT:-8080}:80
    depends_on:
      - app
